### ISSUE TITLE
Comparision with pytest-molecule

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#1]
Few minutes ago I found about tox-ansible project and I find it funny that I see that it originated from the same need as [pytest-molecule](https://github.com/ansible-community/pytest-molecule) one: to allow user to discover and run available molecule tests.

Most of the functionality overlaps but it would make sense to write a clear comparison of pros and cons of each one.

# tox-ansible
* uses tox as orchestrator
* cannot run multiple scenarios with a single command
* unable to expose driver type used by scenarios (or to filter by it)

# pytest-molecule
* uses pytest as orchestrator
* does not cover for variance of python or ansible versions, this being taken care by tox or similar tools.
* can run multiple scenarios with a single command
* More complex command to run `pytest -k scenarioname` or something like `tox -e molecule -- -k scenarioname` when run from inside tox.

Both tools can be used in CI/CD scenarios but sadly the repository maintainer still needs to manually add individual jobs for each scenario to be tested. I am not aware of any CI/CD system that could explode a test matrix generating a new sub-job for each scenario listed in a repository, mainly because they have static configurations.

**Comment by greg-hellings** [comment]
I won't attempt to write the comparison bit, as I haven't used pytest-molecule myself. I've never really learned pytest itself, and didn't discover pytest-molecule until tox-ansible was already decently mature. However, I'd be happy to collaborate with you on a comparison between the two.

> Few minutes ago I found about tox-ansible project and I find it funny that I see that it originated from the same need as [pytest-molecule](https://github.com/ansible-community/pytest-molecule) one: to allow user to discover and run available molecule tests.
> 
> Most of the functionality overlaps but it would make sense to write a clear comparison of pros and cons of each one.
> # tox-ansible
> 
>     * uses tox as orchestrator
> 
>     * cannot run multiple scenarios with a single command

This isn't particularly true. Tox allows you to run multiple environments by specifying them on the command line. So if you wanted to run scenarios "foo" and "bar" in role "my_role" then you could do `tox -e my_role-foo,my_role-bar` and run both. If you want to run every scenario in a collection with the name "default" then you can use the custom tox-ansible filters and do something like `tox --ansible-scenario default`. To run all of the scenarios in the role "my_role" then `tox --ansible-role my_role`.

> 
>     * unable to expose driver type used by scenarios (or to filter by it)

I don't expose it to the user, but you can filter on it. We use this filter in almost all of our scenarios: `tox --ansible-driver docker` for GitHub Actions and `tox --ansible-driver openstack` when we run in Jenkins

> 
> 
> # pytest-molecule
> 
>     * uses pytest as orchestrator
> 
>     * does not cover for variance of python or ansible versions, this being taken care by tox or similar tools.
> 
>     * can run multiple scenarios with a single command
> 
>     * More complex command to run `pytest -k scenarioname` or something like `tox -e molecule -- -k scenarioname` when run from inside tox.
> 
> 
> Both tools can be used in CI/CD scenarios but sadly the repository maintainer still needs to manually add individual jobs for each scenario to be tested. I am not aware of any CI/CD system that could explode a test matrix generating a new sub-job for each scenario listed in a repository, mainly because they have static configurations.

This point isn't entirely true. When I added the `--ansible-driver` option, it was because I discovered that GitHub Actions allows exactly the scenario you are describing. Also because I did a little bit of abusing on the internal tox filter mechanism so you can do `tox --ansible-driver docker -l` and get a list of only the environments containing scenarios that use the "docker" driver, rather than a list of all tox environments.

If you look at [line 37](https://github.com/oasis-roles/ansible_collection_system/blob/master/.github/workflows/tox.yml#L37) of the OASIS System collection CI/CD you'll see where I explode the the list of tox environments that run against Docker and construct a rudimentary JSON object out of them. At the end of that action I set the resulting JSON value to a GitHub action output variable. The whole loop depends on none of the role or scenario names including JSON string special characters in their names, but for my own collections that seems reasonable enough.

Then, down on line 54, the output from the "collect" job is used as the input of the matrix for the "build" job. Originally we had to maintain a manual list of any roles that had at least one Docker scenario, and then run all of its Docker scenarios in a action instance using `tox --ansible-role ${{ matrix.role }}`. But, with this dynamic step, we now run every scenario in its own GA runner by calling `tox -e ${{ matrix.scenario }}`. The "scenario" name is a little bit of a misnomer, as it's really a tox environment name consisting of [role_name]-[scenario_name], but it works.

For this to work in GA, it's imperative to have a two step build, here called "collect" and "build" and on line 49 we set `needs: collect` for the second step. The first step, on line 17, defines its outputs to be the JSON object that we construct at the end of that build stage. "release" is then further gated after "build" so that any tagged item automatically becomes a release.

A similar mechanism is used in Jenkins, where the Jenkinsfile can run arbitrary Groovy actions to define the build matrix. In the Jenkinsfile in that repository you can see that `tox --ansible-driver openstack -l` is invoked and its stdout is split. Each line is the used to create a fan out step in the runner. A callback to GitHub is invoked first, to tell it that the particular scenario is pending, then each scenario subsequently reports success or failure when it has completed. Within our infrastructure, the only line that needs to be modified between different collections is line 18, where the collection name is specified as the checkout path. Obviously, if someone is running in a different set of infrastructure, they might need to change other values in there surrounding OpenShift variables, the specific OASIS values related to RHEL and RHSM, etc. However, on the whole, that Jenkinsfile can serve as a reasonable basis for how a dynamic matrix can be defined in a Jenkins pipeline as well.

**Comment by ssbarnea** [comment]
Thanks for the explanations. Now I am really going to dig bit more into tox-ansible because I like it more, I want to see if it would prove easier to use than pytest option.

One thing is for sure, far more developers are used to tox than are used to pytest and doing "tox -l" and similar commands is much easier than pytest variants.

BTW, Have you considered moving the plugin under tox-dev organization in order to improve its discoverability? I am doing a similar move with my pytest-molecule as I already requests the transfer.

**Comment by greg-hellings** [comment]
I have considered moving it to somewhere with community access. I wasn't sure if tox-dev or ansible-community would be more appropriate.

**Comment by ssbarnea** [comment]
@greg-hellings I am not sure which one is better. I can help you with move to ansible-community as I can transfer projects there if I am made owner. For tox-dev I cannot but I know the maintainer and I can ask, I doubt he would have anything against as he is more than happy to see an increase in number of potential contributors to tox.

I am more than happy to become a core on the project as I am already considering adopting it for tripleo jobs

**Comment by greg-hellings** [comment]
@ssbarnea I would be happy with either destination, and I would love to have more collaboration on this. My team has looked through it, but so far there hasn't been anyone with need to contribute more.

There are things I would like to shore up, like more extensive testing, maybe moving to pytest, and migrating away from some Java-isms and towards more Python style (I made extensive use of getters/setters instead of `@property` methods and have been slowly migrating those). I was waiting until I got through that before I dubbed a 1.0, but the CLI and ini-file interfaces have been stable for a while. Not because I'm against changing it, just because it's covered all of our use cases so far.

If we'd like to choose a shared location, I am happy to add you as a collaborator for it.

**Comment by ssbarnea** [comment]
Lets go for "ansible-community" as the host, as it has few advantages: more visibility to ansiblers and also ability to use more resources, like Zuul CI, if we ever want.

Make me the owner so I can perform the transfer. I am not an organization admin but keep in mind that @gundalow is and he is found on irc and responds very quickly.

**Comment by gundalow** [comment]
Sounds good

**Comment by greg-hellings** [comment]
Sounds good. I've sent you a collab invite on the repo. We can get PyPI secrets worked out as well after it transfers.

**Comment by ssbarnea** [comment]
@greg-hellings Accepted but you still need to bump me to owner to enable the transfer.

**Comment by greg-hellings** [comment]
For repos in a personal space instead of an org, there isn't an option to set access level. "Collaborator" is the only level. So I can transfer to you, then you can transfer it in, if you have create repo access in the org. Otherwise I will need to go first to someone who does (I assume @gundalow).

**Comment by ssbarnea** [comment]
Sure. no problem with me. I was not aware of this difference between personal and orgs. IMHO they were the same. The reality is that I almost never create a project in personal repo unless is really personal, that may explain my lack of "personal" experience.

**Comment by greg-hellings** [comment]
I was also unaware of it until this attempt!
