### ISSUE TITLE
Avoid creating multiple environments for each scenario

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#12]
Instead of created individual environments for each scenario, tox-ansible should use a single one (or limited number), avoiding extra time needed to install and disk footprint.

This issue is particularly important for development environments and if the user has 10...100 scenarios it becomes impossible to deal with the space waste.

![footprint](https://sbarnea.com/ss/Screen-Shot-2020-08-20-11-33-09.03.png)

Based on how we used molecule in openstack tripleo, I am inclined to propose using "molecule" environment for this.

@greg-hellings I will let you drive this as you already know the internals better and how is currently used in the wild.

**Comment by greg-hellings** [comment]
If you set `envdir` in your tox.ini you can force environments to use the same directory. This plugin will not overwrite that value.

There are a few caveats to this - the environment will be recreated if any two scenarios have different drivers, as tox-ansible will set the dependencies to include molecule-{drivername}, which will result in a rebuild of the environment. Not a problem if you're running in series (you'll incur a small performance hit each time it switches environments), but if you're running tox with "-p N" where N > 1, this becomes an issue as one run will be trying to recreate the environment out from under the others. The same risk holds true if any scenario directory contains a requirements.txt file, as that will also be added to the requirements for building that scenario.

I'm not sure if the proper solution is programmatic or not. For now, I left it up to the user to override in their `[testenv]` configuration.

**Comment by ssbarnea** [comment]
The multiple drivers issue can be deferred for another time as I am sure there are ways to avoid it.

Still, what worries me is that in order to avoid creation of additional environments I need to explicitely modify tox.ini file for each new scenario, to add stuff like:

```
[testenv:scenario0]
envdir = {toxworkdir}/molecule

[testenv:scenario1]
envdir = {toxworkdir}/molecule

[testenv:scenario2]
envdir = {toxworkdir}/molecule
```

This does not scale well at all, and it is not possible/safe to change the envdir from the root `[testenv]` section, as it would break the other unamanged envs.

I can understand that maybe you do want to keep the current isolation as default behavior, but we still need to find an opt-in solution for the heavy-scenario users.

**Comment by greg-hellings** [comment]
A few spit-ball ideas:

1) We could avail ourselves of tox's ability to switch things based on environment name components. For instance, instead of `{python}-{ansible}-{role}-{scenario}` we could also include `{driver}` as a component of the name scheme? Then you could do something in tox.ini like this:

```ini
[testenv]
envdir =
    docker: {toxworkdir}/docker
    openstack: {toxworkdir}/openstack
```

2) Not to be exclusive with #1, we could also set a default path such as `{toxworkdir}/{driver}`. It doesn't guarantee freedom from parallel execution problems if a scenario has requirements.txt set, but it gets us closer to the desired state. And anyone with that issue can still use the testenv configuration in tox.ini to explicitly state a path for their scenrio.

One or both of those solutions could address what you're looking for. Another could be to collapse all the Python requirements down into a single list, and anyone who is using any driver gets all of the supported ones by default. Then we can go back to the idea of all of them living in `{toxworkdir}/molecule`.

Do you have a preference?

**Comment by greg-hellings** [comment]
I am also well motivated to figure out a better way forward. A partial run this morning of one collection:

```bash
$ du -sh .tox
4.7G	.tox
```

**Comment by ssbarnea** [comment]
Closing as current behavior of the main branch is to use a single environment. Still, we may need to expand it a bit for the case where user wants to test with specific factors.
