### ISSUE TITLE
Unable to detect scenarios hosted in root folder

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#13]
Molecule scenarios are not exclusively hosted inside roles as they can span across multiple roles or apply to standalone playbooks as well.

Based on my testing it seems that current discovery logic is to look only inside `roles/` folder for scenarios and ignore repositories that have `molecule` folder at root.

For example the discovery logic I used with [pytest-molecule](https://github.com/ansible-community/pytest-molecule/blob/master/pytest_molecule/__init__.py#L122) allowed it to discover all scenarios, regardless if they were hosted at root or deeper level. Still, that implementation is dependent on pytest one so we cannot use it here.

One good example of complex repository that has scenarios in multiple places can be seen at https://github.com/rdo-infra/ci-config/ -- that being one actively used by our team.

**Comment by greg-hellings** [comment]
So currently the code branches based on the presence of galaxy.yml - if it finds it in the root folder, it assumes we're in a collection and only looks under `./roles/*/molecule/*/molecule.yml` for scenarios. Otherwise it checks for the existence of `./tasks/main.yml` to see if it is in a role and, if so, pulls scenarios from `./molecule/*/molecule.yml`.

It's probably incorrect to assume that one or the other of those *must* be true. Also, there is an if/elif conditional that limits it to only supporting one or the other scenario, and not both.

There is lots of breadth for improving the discovery of scenarios.

**Comment by ssbarnea** [comment]
Another discovery approach that is used by ansible-lint itself can be seen at https://github.com/ansible/ansible-lint/blob/42e682dba3fe8b358caf008cc64040555c06453c/lib/ansiblelint/utils.py#L668 -- basically it uses git to retrieve all yaml files and filters them. I suggest doing the same and looking for the official `molecule/*/molecule.yml` pattern inside.
