### ISSUE TITLE
Reconsider switching license from GPLv3 to MIT to match tox

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#27]
I think it would be a good idea to switch project license to MIT in order to match tox own license.

I am worries that current license could work against the project as some users may not want to bundle the plugin and distribute it (I have containers in mind).

@greg-hellings What do you think?

**Comment by greg-hellings** [comment]
I generally like to go with the most permissible license possible. I default to GPLv3, though, just because it's the only one that I don't get confused by. I have no objections to any other, as long as you and I agree. It looks like we're the only authors at this point, so our legal duty is fulfilled as long as we're in agreement on a license change. Matching tox's license seems the most reasonable, due to the nature of a plugin.
